# Change these first
owner: occustar # Your GitHub organization or username, where this repository lives
repo: ors_status # The name of this repository

sites:
  - name: Testing
    url: https://testing.occustarsecure.com
  - name: Scheduling
    url: https://scheduling.occustarsecure.com
  - name: Beta
    url: beta.occustarsecure.com
  - name: Client
    url: client.occustarsecure.com


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /ors_status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: OCCUSTAR Status
  introTitle: "**OCCUSTAR Status** — real-time uptime monitor"
  introMessage: Public Status page for Occustar 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
